version: "3.5"
services:
  pgsql:
    container_name: sp-db
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd!
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    container_name: sp-backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_PORT=8080
      - BACKEND_PORT=3000
      - DB_HOST=pgsql
      - DB_NAME=snackpass
      - DB_USER=postgres
      - DB_PASS=P@ssw0rd!  # please don't put passwords here in real life :(
    volumes:
      - ./backend:/app
    depends_on:
      - pgsql
  frontend:
    container_name: sp-frontend
    build: ./frontend
    ports: 
      - "80:1234"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend